name: Test Suite

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        SCIDB_VER: [19.11]
        OS: [xenial, centos-7]
        python-version: [3.6, 3.7, 3.8, 3.9]

    services:
      scidb:
        image: ghcr.io/rvernica/scidb:${{ matrix.SCIDB_VER }}-${{ matrix.OS }}
        volumes:
          - /dev/shm
          - /home/runner/work:/__w
          - /sys/fs/cgroup:/sys/fs/cgroup
          - /tmp/$(mktemp --directory):/run
          - /tmp:/tmp
        ports:
          - 8080:8080
          - 8083:8083
        env:
          ARROW_VER: 3.0.0
        options: --name scidb

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup client
        run: pip install scidb-py

      - name: Start SciDB in CentOS-7
        run: >-
          docker exec scidb
          /opt/scidb/${{ matrix.SCIDB_VER }}/bin/scidbctl.py start scidb
        if: ${{ matrix.OS == 'centos-7' }}

      - name: Start Shim in CentOS-7
        run: docker exec scidb systemctl start shimsvc
        if: ${{ matrix.OS == 'centos-7' }}

      - name: Wait for SciDB to start
        run: while ! curl http://localhost:8080/version; do sleep 5; done

      - name: Set-up Docker container
        run: >-
          docker exec scidb
          /__w/accelerated_io_tools/accelerated_io_tools/tests/docker-install.sh

      - name: Run tests 1/3
        run: >-
          docker exec scidb
          /__w/accelerated_io_tools/accelerated_io_tools/tests/test.sh

      - name: Run tests 2/3
        run: >-
          docker exec scidb
          /__w/accelerated_io_tools/accelerated_io_tools/tests/test-skip.sh

      - name: Run tests 3/3
        run: >-
          docker exec scidb
          /__w/accelerated_io_tools/accelerated_io_tools/tests/test_arrow.sh

      - name: Run tests from client
        run: ./tests/test_arrow.sh "docker exec scidb"
