name: Test w/ SciDB EE

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    services:
      scidb:
        image: ghcr.io/paradigm4/centos-7-3rdparty:21.8
        volumes:
          - /home/runner/work/accelerated_io_tools:/__w
          - /sys/fs/cgroup:/sys/fs/cgroup
          - /tmp/$(mktemp --directory):/run
          - /tmp:/tmp
        ports:
          - 8080:8080
          - 8083:8083
        options: --name scidb

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup client
        run: pip install scidb-py

      - name: Install SciDB, use 4 instances, enable aio in Shim
        run: |
          docker exec scidb /root/install-scidb.sh ${{ secrets.P4_USERNAME }} ${{ secrets.P4_PASSWORD }}
          echo "Update config"
          docker exec scidb sed --in-place s/server-0=127.0.0.1,1/server-0=127.0.0.1,3/ /opt/scidb/21.8/etc/config.ini
          echo "Init SciDB"
          docker exec scidb /root/init-scidb.sh
          echo "Install Shim"
          docker exec scidb /root/install-shim.sh v21.8
          docker exec scidb bash -c "echo aio=1 >> /var/lib/shim/conf"

      - name: Start SciDB
        run: |
          docker exec scidb scidbctl.py start
          docker exec scidb systemctl restart shimsvc
          while ! curl http://localhost:8080/version; do sleep 1; done

      - name: Make, Install, and Load accelerated_io_tools
        run: |
          docker exec scidb scl enable devtoolset-9 "make --directory=/__w/accelerated_io_tools"
          docker exec scidb cp /__w/accelerated_io_tools/libaccelerated_io_tools.so /opt/scidb/21.8/lib/scidb/plugins/
          docker exec scidb iquery --afl --query "load_library('accelerated_io_tools')"

      - name: Setup Python dependencies
        run: |
          docker exec scidb pip3 install --upgrade pip
          docker exec scidb pip3 install scidb-py

      - name: Run tests 1/3
        run: >-
          docker exec scidb
          /__w/accelerated_io_tools/tests/test.sh

      - name: Run tests 2/3
        run: >-
          docker exec scidb
          /__w/accelerated_io_tools/tests/test-skip.sh

      - name: Run tests 3/3
        run: >-
          docker exec scidb
          /__w/accelerated_io_tools/tests/test_arrow.sh

      - name: Run tests from client
        run: ./tests/test_arrow.sh "docker exec scidb"
